# app/config/routing.yaml

# AppBundle

app:
    resource: "@AppBundle/Controller"
    type:     annotation

# SonataBundle

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /femida

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /femida

# Liip

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
