# app/config/security.yml
security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
          - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT

    providers:
        in_memory:
            memory:
                users:
                    femida:
                        password: $2y$12$DCNzUmczZ27Jyrd43wtgJu5RSTVuyMIbmmgIikpNOOS6L9tD.NKf6
                        roles:    'ROLE_ADMIN'

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost:      12

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            http_basic: ~
            logout:
                success_handler: logout_listener

    access_control:
        - { path: ^/femida, roles: ROLE_ADMIN }
